// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function CreateVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVersion'](arg1, arg2, arg3);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function Diff(arg1, arg2) {
  return window['go']['main']['App']['Diff'](arg1, arg2);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListVersions(arg1) {
  return window['go']['main']['App']['ListVersions'](arg1);
}

export function QualityTrend(arg1) {
  return window['go']['main']['App']['QualityTrend'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function Rollback(arg1, arg2) {
  return window['go']['main']['App']['Rollback'](arg1, arg2);
}
