// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {api} from '../models';

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<db.PromptDoc>;

export function CreateVersion(arg1:string,arg2:string,arg3:string):Promise<db.PromptVersion>;

export function DeletePrompt(arg1:string):Promise<void>;

export function Diff(arg1:string,arg2:string):Promise<api.DiffResult>;

export function GetAPIURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetPrompt(arg1:string):Promise<db.PromptDoc>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function ListPrompts():Promise<Array<db.PromptDoc>>;

export function ListVersions(arg1:string):Promise<Array<db.PromptVersion>>;

export function QualityTrend(arg1:string):Promise<Array<api.VersionQuality>>;

export function Quit():Promise<void>;

export function RevokeKey(arg1:string):Promise<void>;

export function Rollback(arg1:string,arg2:string):Promise<db.PromptDoc>;
